name: Action
on:
  push:
    branches:
  pull_request:
    branches:
jobs:
  test:
    name: TestName
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: run echoes
        shell: bash
        run: echo ${{ matrix.os }}